base_url = "https://0xc1.space"
title = "c1 的博客"
description = "c1 的博客"
compile_sass = false
minify_html = true
generate_feeds = true
default_language = "zh"

taxonomies = [{ name = "tags", feed = true }]

# [languages.en]
# weight = 2
# languageName = "Englisch"
# languageCode = "en"

[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_code = false
highlight_theme = "gruvbox-dark"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[link_checker]
internal_level = "warn"

[extra]
author = "0xc1"
display_author = true
google_analytics = "G-8DQTX42T4P"

favicon = "favicon.ico"
image = ""

default_theme = "light"
list_pages = false
twitter_card = true

header_nav = [
  { url = "/blog", name_zh = "|博客|", name_en = "/blog/" },
  { url = "/gcores-talks", name_zh = "|机组|", name_en = "/gcores-talk/" },
  { url = "/about", name_zh = "|关于|", name_en = "/about/" },
]

# Optional footer license text. It will only show, when using footer_content_license.
#footer_content_license = "Creative Commons Attribution 4.0 International"
#footer_content_license_link = "https://creativecommons.org/licenses/by/4.0/"
