# On every push or daily schedule this script is executed
on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight UTC

name: Update Gcores Talks

jobs:
  update-gcores-talks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run get-gcores-talk.ts
        run: deno run --allow-net --allow-read --allow-write ./scripts/get-gcores-talk.ts --json ./data/gcores-talks.json

      - name: Check for changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ./data/gcores-talks.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

      - name: Commit and push changes
        run: |
          git commit -m "Update gcores-talks.json"
          git push origin master
          echo "Changes committed and pushed."
